import type { Metadata } from "next";
import { Figtree } from "next/font/google";
import "./globals.css";
import Providers from "./providers";
import { Toaster } from "react-hot-toast";

const figtree = Figtree({
  weight: ["300", "400", "500", "600", "700", "800", "900"],
  variable: "--font-figtree",
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${figtree.variable} antialiased`}
        style={{ fontFamily: figtree.style.fontFamily }}
      >
        <Providers>{children}</Providers>
        <Toaster />
      </body>
    </html>
  );
}
